"""Generate the complete Mathlib-only proof without importing local oleans."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
LEAN = ROOT / 'lean'
OUTPUT = ROOT / 'lean4web/TachikawaCharZeroLean4Web.lean'
IMPORT = re.compile(r'^(?:(?:public|meta)\s+)*import\s+([^\n]+)$', re.M)


def generate():
    visited, sources = set(), []

    def visit(module):
        if module in visited:
            return
        path = LEAN.joinpath(*module.split('.')).with_suffix('.lean')
        if not path.is_file():
            path = LEAN / 'vendor/openai-math/lean'
            path = path.joinpath(*module.split('.')).with_suffix('.lean')
        if not path.is_file():
            if module.startswith(('Tachikawa', 'OAI.')):
                raise ValueError('Missing project source: ' + module)
            return
        visited.add(module)
        text = path.read_text()
        for match in IMPORT.finditer(text):
            for dependency in match.group(1).split('--', 1)[0].split():
                visit(dependency)
        body = IMPORT.sub('', text)
        body = re.sub(r'^(?:module|@\[expose\] public section)\s*\n',
                      '', body, flags=re.M).strip()
        # Lean 4.35 renamed the conditional reduction lemmas. Keep native
        # sources unchanged and adapt only the generated standalone text.
        for old, new in [('if_pos', 'ite_eq_left'), ('if_neg', 'ite_eq_right'),
                         ('dif_pos', 'dite_eq_left'), ('dif_neg', 'dite_eq_right')]:
            body = re.sub(r'\b' + old + r'\b', new, body)
        # Independent upstream excerpts repeat some public helper names.
        # Separate module imports permit these overlaps; inlining must rename
        # the later copy and its local uses.
        if module.endswith('.IntegerTensorSupport'):
            for name in ['map_id_underlying', 'map_id_right_underlying',
                         'exact_map_left', 'exact_map_right']:
                body = re.sub(r'\b' + name + r'\b', 'webInteger_' + name, body)
        if module.endswith('.OrthogonalDescent'):
            body = re.sub(r'\bkProjective_chain_representative\b',
                          'webOrthogonal_chain_representative', body)
        if module.endswith('.EvaluationInduction'):
            body = re.sub(r'\bres_map_exact\b', 'webEvaluation_res_map_exact', body)
        if module in ['TachikawaCharZero.BInjectiveDimension',
                      'TachikawaCharZero.RestrictionDimension',
                      'TachikawaCharZero.RestrictedPerfect']:
            body = '\n'.join(line if line.lstrip().startswith('open ') else
                             re.sub(r'(?<![\w.])transportResolution\b',
                                    'TensorDualResolution.transportResolution', line)
                             for line in body.splitlines())
        if module == 'TachikawaCharZero.TwistedOrthogonality':
            body = re.sub(r'(?<![\w.])InAdd\b', 'TwistedBimoduleObstruction.InAdd', body)
        if module.endswith('.Coresolution'):
            body = body.replace('(by simp; rfl)', '(by simp <;> rfl)')
        if module == 'TachikawaCharZero.SocleBimodule':
            old = '''((inclusionBE (@algebraMap ℚ BE _ (inferInstance : Semiring BE) inferInstance c)) •
        (show S from f))'''
            new = '''(@SMul.smul EE S S.isModule.toSMul
        (inclusionBE (@algebraMap ℚ BE _ (inferInstance : Semiring BE) inferInstance c))
        (show S from f))'''
            assert old in body
            body = body.replace(old, new)
        models = {'TachikawaCharZero.EvaluatedCosyzygy': 'YXModel.obj',
                  'TachikawaCharZero.EvaluatedCokerComparison': 'inducedYModel.obj',
                  'TachikawaCharZero.CornerTensorModel': 'Y.obj'}
        if module in models:
            old = 'ModuleCat.ofHom (fixedYComparison.hom.comp (FixedYEvaluation.evaluatedLift H hH).hom)'
            new = ('ConcreteCategory.ofHom (C := ModuleCat E) (X := X) (Y := '
                   + models[module] + ')\n'
                   '    (fixedYComparison.hom.comp (FixedYEvaluation.evaluatedLift H hH).hom)')
            assert old in body
            body = body.replace(old, new)
        relative = path.relative_to(LEAN).as_posix()
        sources.append((relative, body))

    visit('Tachikawa')
    header = '''import Mathlib

/-!
# Characteristic-zero Tachikawa: complete standalone proof

Generated by lean/scripts/make_lean4web.py. The only external import is Mathlib.
The final public theorems are `TachikawaCharZero.tachikawaSecondConjecture`
and `TachikawaCharZero.artinAuslanderReiten`.

The native source project pins Lean v4.34.1. This standalone port pins
Lean v4.35.0-rc4 and Mathlib 021ce68bf125a049beee22b3fc7664d78728e21d.
Select a compatible Lean4Web project.
Each source module is enclosed in a section to restore its local options,
opens, variables, and instances before processing the next source module.
See README.md for the actual verification status and browser limitations.
-/

#eval Lean.versionString
'''
    content = header + '\n\n'.join(
        '\n-- Source: ' + name + '\nsection\n' + body + '\nend\n'
        for name, body in sources
    ) + '\n'
    OUTPUT.write_text(content)
    print('Generated', OUTPUT.name, len(sources), 'modules,',
          len(content.splitlines()), 'lines')


if __name__ == '__main__':
    generate()
